<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/30
 * Time: 上午11:45
 */

namespace app\modules\app\actions;


use app\modules\app\components\AppAction;
use common\models\ar\UyeUserContact;
use components\CheckUtil;
use components\Output;
use components\UException;

class ContactAction extends AppAction
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function run()
    {
        try {
            $params = [
                'home_province' => $this->getParams('home_province'),
                'home_city' => $this->getParams('home_city'),
                'home_area' => $this->getParams('home_area'),
                'home_address' => $this->getParams('home_address'),
                'email' => $this->getParams('email'),
                'wechat' => $this->getParams('wechat'),
                'qq' => $this->getParams('qq'),
                'contact1_relation' => $this->getParams('contact1_relation'),
                'contact1_name' => $this->getParams('contact1_name'),
                'contact1_phone' => $this->getParams('contact1_phone'),
                'marriage' => $this->getParams('marriage'),
            ];

            foreach ($params as $key => $param) {
                if (empty($param)) {
                    throw new UException(ERROR_SYS_PARAMS_CONTENT . ':' . $key . "=>" . $param, ERROR_SYS_PARAMS);
                }
            }

            if (mb_strlen($params['home_address']) > 64 || mb_strlen($params['home_address']) < 3) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ":请填写详细住址", ERROR_SYS_PARAMS);
            }

            if (!CheckUtil::checkEmail($params['email'])) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ":请填写正确电子邮箱地址", ERROR_SYS_PARAMS);
            }

            if (!CheckUtil::phone($params['contact1_phone'])) {
                throw new UException(ERROR_PHONE_FORMAT_CONTENT, ERROR_PHONE_FORMAT);
            }

            if (!CheckUtil::checkFullName($params['contact1_name'])) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ":请填写中文姓名", ERROR_SYS_PARAMS);
            }

            if (mb_strlen($params['contact1_name']) > 10 || mb_strlen($params['contact1_name']) < 2) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ":请正确填写联系人中文姓名", ERROR_SYS_PARAMS);
            }

            $userInfo = UyeUserContact::getUserInfo($this->uid);
            if (empty($userInfo)) {
                $params['uid'] = $this->uid;
                $userInfo = UyeUserContact::_add($params);
            }

            $diff = [];
            foreach ($params as $key => $val) {
                if (array_key_exists($key, $userInfo) && $val != $userInfo[$key]) {
                    $diff[$key] = $val;
                }
            }

            if (!empty($diff)) {
                UyeUserContact::_update($this->uid, $diff);
            }
            Output::info(SUCCESS, SUCCESS_CONTENT);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}