<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/30
 * Time: 下午4:48
 */

namespace app\modules\app\actions;


use app\modules\app\components\AppAction;
use common\models\ar\UyeUserExperienceList;
use components\Output;
use components\UException;

class ElistAction extends AppAction
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function run()
    {
        try {
            $params = [
                'type' => $this->getParams('type'),
                'date_start' => $this->getParams('date_start'),
                'date_end' => $this->getParams('date_end'),
            ];

            if ($params['type'] == UyeUserExperienceList::TYPE_STUDY) {
                $params['school_name'] = $this->getParams('school_name');
                $params['education'] = $this->getParams('education');
                $params['school_profession'] = $this->getParams('school_profession');
                $params['school_address'] = $this->getParams('school_address');
            } else if ($params['type'] == UyeUserExperienceList::TYPE_WORK) {
                $params['work_name'] = $this->getParams('work_name');
                $params['work_position'] = $this->getParams('work_position');
                $params['work_salary'] = $this->getParams('work_salary');
            } else {
                throw new UException(ERROR_SYS_PARAMS_CONTENT, ERROR_SYS_PARAMS);
            }

            foreach ($params as $key => $param) {
                if (empty($param)) {
                    throw new UException(ERROR_SYS_PARAMS_CONTENT . ":" . $key, ERROR_SYS_PARAMS);
                }
            }
            $id = $this->getParams('id');
            if ($id) {

                $old_info = UyeUserExperienceList::getByID($params['id']);
                $diff = [];
                foreach ($params as $key => $param) {
                    if (array_key_exists($key, $old_info) && $param != $old_info[$key]) {
                        $diff[$key] = $param;
                    }
                }

                if (empty($diff)) {
                    UyeUserExperienceList::_update($id, $diff);
                }
            } else {
                $params['uid'] = $this->uid;
                UyeUserExperienceList::_add($params);
            }
            Output::info(SUCCESS, SUCCESS_CONTENT);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}