<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/12
 * Time: 下午7:51
 */

namespace app\modules\app\actions;


use app\modules\app\components\AppAction;
use common\models\ar\UyeUserQuestion;
use components\Output;
use components\UException;
use frontend\models\DataBus;

class QuestionAction extends AppAction
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function run()
    {
        try {
            $uid = DataBus::get('uid');
            $org_id = $this->getParams('org_id');
            $question = $this->getParams('question');
            if (empty($org_id) || !is_numeric($org_id) || empty($question) || !is_array($question)) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT, ERROR_SYS_PARAMS);
            }

            $userQuestion = UyeUserQuestion::find()->select('*')->where('uid=:uid AND org_id=:org_id', [':uid' => $uid, 'org_id' => $org_id])->asArray()->one();
            if (empty($userQuestion)) {
                UyeUserQuestion::_add(['uid' => $uid, 'org_id' => $org_id, 'question' => json_encode($question)]);
            } else {
                throw new UException(ERROR_USER_QUESTION_EXISTS_CONTENT, ERROR_USER_QUESTION_EXISTS);
            }
            Output::info(SUCCESS, SUCCESS_CONTENT);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}