<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/11
 * Time: 下午3:26
 */

namespace app\modules\app\actions;


use app\modules\app\components\AppAction;
use common\models\ar\UyeUserContact;
use common\models\ar\UyeUserIdentity;
use components\Output;
use components\UException;
use frontend\models\DataBus;

class UserinfoAction extends AppAction
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function run()
    {
        try {
            $identity = $this->identity($this->uid);
            $contact = $this->contact($this->uid);
            $templateData = [
                'identity' => $identity,
                'contact' => $contact,
            ];
            Output::info(SUCCESS, SUCCESS_CONTENT, $templateData);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }

    private function identity($uid)
    {
        $userIdentity = UyeUserIdentity::find()->select('*')->where('uid=:uid', [':uid' => $uid])->asArray()->one();
        if (empty($userIdentity)) {
            return false;
        }

        $params = ['full_name', 'id_card', 'id_card_start', 'id_card_end', 'id_card_address', 'id_card_info_pic', 'id_card_nation_pic', 'auth_mobile', 'bank_card_number', 'open_bank_code', 'open_bank'];

        $result = true;
        foreach ($params as $param) {
            if (!array_key_exists($param, $userIdentity) || empty($userIdentity[$param])) {
                $result = false;
                break;
            }
        }
        return $result;
    }

    private function contact($uid)
    {
        $userContact = UyeUserContact::getUserInfo($uid);
        if (empty($userContact)) {
            return false;
        }

        $params = ['home_province', 'home_city', 'home_area', 'home_address', 'email', 'wechat', 'qq', 'contact1_name', 'contact1_phone', 'contact1_relation', 'marriage'];
        $result = true;
        foreach ($params as $param) {
            if (!array_key_exists($param, $userContact) || empty($userContact[$param])) {
                $result = false;
                break;
            }
        }
        return $result;
    }

}