<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/19
 * Time: 下午3:55
 */

namespace common\models\search;


use common\models\ar\UyeAppVersion;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class UyeAppVersionSearch extends UyeAppVersion
{
    public function rules()
    {
        return [
            [['id', 'type', 'version_code', 'size', 'force_update', 'status', 'created_time'], 'integer'],
            [['version_name', 'desp', 'url'], 'safe'],
        ];
    }


    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = UyeAppVersion::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere([]);

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'type' => $this->type,
            'version_code' => $this->version_code,
            'size' => $this->size,
            'force_update' => $this->force_update,
            'status' => $this->status,
            'created_time' => $this->created_time,
        ]);

        $query->andFilterWhere(['like', 'version_name', $this->version_name])
            ->andFilterWhere(['like', 'desp', $this->desp])
            ->andFilterWhere(['like', 'url', $this->url]);

        return $dataProvider;
    }


}