<?php

namespace frontend\controllers;


use components\CheckUtil;
use components\Output;
use components\SmsUtil;
use components\UException;
use frontend\components\UController;
use frontend\models\DataBus;
use frontend\models\UyeUserModel;
use Yii;

class LoginController extends UController
{
    private $ip = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->isLogin()) {
            if ($this->isMobile) {
                Output::err(ERROR_LOGIN_ING, ERROR_LOGIN_ING_CONTENT, array(), $this->uid);
            } else {
                Output::err(ERROR_LOGIN_ING, ERROR_LOGIN_ING_CONTENT, array(), $this->uid);
            }
        }
        $this->ip = Yii::$app->request->getUserIP();
    }

    /**
     * 普通密码登陆
     */
    public function actionLogin()
    {
        try {
            $request = Yii::$app->request;
            $phone = $request->post() ? $request->post('phone') : $request->get('phone');
            $password = $request->post() ? $request->post('password') : $request->get('password');
            $phoneid = $request->post() ? $request->post('phoneid', '') : $request->get('phoneid', '');
            $userInfo = UyeUserModel::login($phone, $password, $phoneid);
            if ($this->isMobile) {
                $userInfo['cookie'] = $this->getCookie();
            }
            Output::info(SUCCESS, '登录成功', $userInfo);
        } catch (\Exception $exception) {
            Output::err($exception->getCode(), $exception->getMessage(), array(), $this->uid);
        }
    }

    /**
     * 短信验证码登录
     */
    public function actionLoginphone()
    {
        try {
            $request = Yii::$app->request;
            $phone = $request->post() ? $request->post('phone') : $request->get('phone');
            $code = $request->post() ? $request->post('code') : $request->get('code');
            $phoneid = $request->post() ? $request->post('phoneid', '') : $request->get('phoneid', '');
            SmsUtil::checkVerifyCode($phone, $this->ip, $code);
            $userInfo = UyeUserModel::loginByPhoneCode($phone, $phoneid);
            if ($this->isMobile) {
                $userInfo['cookie'] = $this->getCookie();
            }
            Output::info(SUCCESS, '登录成功', $userInfo);
        } catch (\Exception $exception) {
            Output::err($exception->getCode(), $exception->getMessage(), array(), $this->uid);
        }
    }

    /**
     * 注册
     */
    public function actionRegister()
    {
        try {
            $request = Yii::$app->request;
            $phone = $request->post() ? $request->post('phone') : $request->get('phone');
            $code = $request->post() ? $request->post('code') : $request->get('code');
            $password = $request->post() ? $request->post('password') : $request->get('password');
            $phoneid = $request->post() ? $request->post('phoneid', '') : $request->get('phoneid', '');
            if (!CheckUtil::phone($phone)) {
                throw new UException(ERROR_PHONE_FORMAT_CONTENT, ERROR_PHONE_FORMAT);
            }

            SmsUtil::checkVerifyCode($phone, $this->ip, $code);

            if (!CheckUtil::isPWD($password)) {
                throw new UException(ERROR_PASSWORD_FORMAT_CONTENT, ERROR_PASSWORD_FORMAT);
            }
            UyeUserModel::register($phone, $password, $phoneid);
            $userInfo = UyeUserModel::login($phone, $password);
            if ($this->isMobile) {
                $userInfo['cookie'] = $this->getCookie();
            }
            Output::info(SUCCESS, SUCCESS_CONTENT, $userInfo);
        } catch (\Exception $exception) {
            Output::err($exception->getCode(), $exception->getMessage(), array(), $this->uid);
        }
    }

    private function getCookie()
    {
        return [
            'PHPSESSID' => session_id(),
            'bjzhongteng_com' => $_COOKIE['bjzhongteng_com'],
            'b42e7_uye_user' => $_COOKIE['b42e7_uye_user'],
        ];
    }

}
