<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/12
 * Time: 下午4:00
 */

namespace frontend\controllers;


use components\Output;
use components\UException;
use frontend\components\UController;
use frontend\models\DataBus;

class UdcreditController extends UController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
//        if ($this->isMobile) {
//            $this->checkLogin();
//        } else {
//            $this->checkLogin(true);
//        }

        try {
            Output::err(SUCCESS, SUCCESS_CONTENT, []);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage(), [], DataBus::get('uid'));
        }

    }
}