<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/18
 * Time: 下午5:32
 */

namespace frontend\controllers;


use components\Output;
use components\UException;
use frontend\components\UController;

class UserController extends UController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }


    public function actionUpdatePassword()
    {
        try {
            $method = $_SERVER['REQUEST_METHOD'];
            if (strtolower($method) != 'post') {
                throw new UException();
            }
            $request = \Yii::$app->request;
            $oldPassword = $request->post('old');
            $newPassword = $request->post('new');


        } catch (\Exception $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}