<?php

namespace frontend\components;


use components\HttpUtil;
use components\Output;
use frontend\models\DataBus;
use yii\web\Controller;
use yii;

class UController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 查询当前登录态
     * @return array|mixed
     */
    protected function isLogin()
    {
        return DataBus::get('isLogin');
    }

    /**
     * 检查是否登录,未登录直接返回错误信息
     * @param bool $toLogin
     * @return array|mixed
     * @throws yii\base\ExitException
     */
    protected function checkLogin($toLogin = false)
    {
        if (!$this->isLogin()) {
            if ($toLogin) {
                HttpUtil::goLogin();
            } else {
                Output::err();
            }
            Yii::$app->end();
        } else {
            return $this->isLogin();
        }
    }
}