<?php

namespace app\modules\e\controllers;

use Yii;
use app\modules\e\components\EController;
use yii\web\HttpException;


/**
 * Default controller for the `e` module
 */
class DefaultController extends EController
{
    public $layout = "main";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }
}
