<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/19
 * Time: 下午4:57
 */

namespace app\modules\e\controllers;


use app\modules\e\components\EController;

class InsuredController extends EController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        
    }
}