<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/19
 * Time: 下午4:58
 */

namespace app\modules\e\controllers;


use app\modules\e\models\EDataBus;
use app\modules\e\models\EuserModel;
use components\CookieUtil;
use yii\web\Controller;

class LoginController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionLogin()
    {
        $phone = \Yii::$app->request->post('phone');
        $password = \Yii::$app->request->post('password');
        if (!empty($phone) && !empty($password)) {
            $userInfo = EuserModel::login($phone, $password);
            $strCode = $userInfo['uid'] . "|" . $userInfo['username'] . "|" . $userInfo['phone'] . '|' . CookieUtil::createSafecv();
            CookieUtil::Cookie(EDataBus::COOKIE_KEY, CookieUtil::strCode($strCode), strtotime('+1 day'));
            $this->redirect('/e/default/index');
        } else {
            $this->layout = 'main';
            return $this->render('login');
        }
    }

    public function actionLogout()
    {
        CookieUtil::Cookie(EDataBus::COOKIE_KEY, '', time() - 3600);
        session_start();
        $_SESSION = array();
        if (isset($_COOKIE[session_name()])) {
            setCookie(session_name(), '', time() - 3600, '/');
        }
        session_destroy();
        $this->redirect('/e/login/login');

    }
}