<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/19
 * Time: 下午2:25
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeAppVersion;
use components\Output;
use components\UException;

class ConfigController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionVersion()
    {
        try {
            if (empty($this->version) || empty($this->plat)) {
                throw new UException(SUCCESS_CONTENT, SUCCESS);
            }
            $newVersion = UyeAppVersion::getVersion('', $this->plat);
            if (is_numeric($this->version) && !empty($newVersion) && $newVersion[0]['version_code'] > $this->version) {
                $data = [
                    'isUpdate' => true,
                    'version_code' => $newVersion[0]['version_code'],
                    'version' => $newVersion[0]['version_name'],
                    'desp' => $newVersion[0]['desp'],
                    'url' => $newVersion[0]['url'],
                    'created_time' => date('Y-m-d H:i:s', $newVersion[0]['created_time']),
                    'size' => round($newVersion[0]['size'] / 1024 / 1024, 1) . 'M',
                    'forceUpdate' => UyeAppVersion::checkForceUpdate($this->version, $this->plat),
                ];
            } else {
                $data = ['isUpdate' => false, 'forceUpdate' => false];
            }
            Output::info(SUCCESS, SUCCESS_CONTENT, $data);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage(), ['isUpdate' => false, 'forceUpdate' => false]);
        }
    }
}