<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/31
 * Time: 上午11:06
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeUserExperienceList;
use components\Output;
use components\UException;

class ElistController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function actions()
    {
        $actions = [
            'submit' => [
                'class' => 'app\modules\app\actions\ElistAction',
            ],
        ];
        return $actions;
    }

    public function actionList()
    {
        try {
            $type = $this->getParams('type');
            if (array_key_exists($type, UyeUserExperienceList::$type)) {
                $list = UyeUserExperienceList::getByUid($this->uid, $type);
            } else {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ':type类型异常', ERROR_SYS_PARAMS);
            }
            Output::info(SUCCESS, SUCCESS_CONTENT, $list);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }

    public function actionConfig()
    {
        try {
            $data = [
                'education' => ['初中及以下', '中专', '高中', '大专', '本科', '硕士', '博士及以上'],
                'position' => ['高层管理人员', '中层管理人员', '基层管理人员', '普通员工'],
                'monthly_income' => ['2000以下', '2000~5000', '5000~8000', '8000~20000', '20000以上'],
            ];

            Output::info(SUCCESS, SUCCESS_CONTENT, $data);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }

    public function actionDel()
    {
        try {
            $id = $this->getParams('id');
            if (empty($id) || !is_numeric($id)) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ":id", ERROR_SYS_PARAMS);
            }

            $list = UyeUserExperienceList::getByID($id);
            if (empty($list) || $list['uid'] != $this->uid) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT . ":经历暂未查询", ERROR_SYS_PARAMS);
            }

            UyeUserExperienceList::_update($id, ['status' => UyeUserExperienceList::STATUS_OFF]);
            Output::info(SUCCESS, SUCCESS_CONTENT);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}