<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/30
 * Time: 下午3:41
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeUserExperience;
use common\models\ar\UyeUserExperienceList;
use components\Output;
use components\UException;

class ExperController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function actions()
    {
        $actions = [
            'submit' => [
                'class' => 'app\modules\app\actions\ExperAction',
            ],
        ];
        return $actions;
    }

    public function actionInfo()
    {
        try {
            $userInfo = UyeUserExperience::getByUid($this->uid);

            if (!empty($userInfo['will_work_city'])) {
                $userInfo['will_work_city'] = json_decode($userInfo['will_work_city'], true);
            } else {
                $userInfo['will_work_city'] = [];
            }
            Output::info(SUCCESS, SUCCESS_CONTENT, $userInfo);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }

    public function actionConfig()
    {
        try {
            $data = [
                'highest_education' => ['初中及以下', '中专', '高中', '大专', '本科', '硕士', '博士及以上'],
                'profession' => ['未就业', '国家机关公务员', '事业单位员工', '企业单位员工', '私营业主', '金融业人员', '医务人员', '服务业人员', '信息技术人员', '教师', '律师', '工程师', '文体业人员', '农民', '其他'],
                'housing_situation' => ['宿舍', '租房', '与父母同住', '与其他亲属同住', '自有住房', '其他'],
                'monthly_income' => ['2000以下', '2000~5000', '5000~8000', '8000~20000', '20000以上'],
            ];
            Output::info(SUCCESS, SUCCESS_CONTENT, $data);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }


}