<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/12
 * Time: 下午5:25
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeConfig;
use common\models\ar\UyeUserAuth;
use common\models\ar\UyeUserIdentity;
use components\Output;
use components\RedisUtil;
use components\UException;
use frontend\models\DataBus;

class IdentityController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function actions()
    {
        return [
            'submit' => [
                'class' => "app\modules\app\actions\IdentityAction"
            ],
        ];
    }

    public function actionInfo()
    {
        try {
            if (empty($this->uid)) {
                throw new UException(ERROR_USER_INFO_NO_EXISTS_CONTENT, ERROR_USER_INFO_NO_EXISTS_CONTENT);
            }
            $userIdentity = UyeUserIdentity::getByUid($this->uid);

            if (empty($userIdentity)) {
                $userIdentity = UyeUserIdentity::_add(['uid' => $this->uid]);
            }
            Output::info(SUCCESS, SUCCESS_CONTENT, $userIdentity);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }

    public function actionConfig()
    {
        try {
            $config = UyeConfig::getConfig('open_bank');
            $data = json_decode($config['value'], true);
            Output::info(SUCCESS, SUCCESS_CONTENT, $data);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }

    public function actionPic()
    {
        try {
            $udcredit_order = $this->getParams('udcredit_order');
            if (empty($udcredit_order)) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT, ERROR_SYS_PARAMS);
            }

            $userInfo = UyeUserAuth::getUserInfoByOrder($udcredit_order);
            if (empty($userInfo)) {
                $data = [
                    'id_card_info_pic' => '',
                    'id_card_nation_pic' => '',
                ];
            } else {
                $data = [
                    'id_card_info_pic' => !empty($userInfo['front_card']) ? DOMAIN_SECRET . $userInfo['front_card'] : '',
                    'id_card_nation_pic' => !empty($userInfo['back_card']) ? DOMAIN_SECRET . $userInfo['back_card'] : '',
                ];
            }

            Output::info(SUCCESS, SUCCESS_CONTENT, $data);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}