<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/19
 * Time: 上午10:29
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeOrg;
use common\models\ar\UyeOrgInfo;

class OrgController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            [
                'class' => 'yii\filters\PageCache',
                'only' => ['view'],
                'duration' => 3600 * 3,
                'variations' => [
                    \Yii::$app->language,
                ],
            ],
        ];
    }

    public function actionView()
    {
        $this->layout = "main_h5";
        $request = \Yii::$app->request;
        $org_id = $request->get('org_id');
        $fields = "oi.description";
        $orgInfo = UyeOrg::find()
            ->select($fields)
            ->from(UyeOrg::TABLE_NAME . " o")
            ->leftJoin(UyeOrgInfo::TABLE_NAME . " oi", "oi.org_id=o.id")
            ->where('o.id=:id AND o.status=:status AND o.is_shelf=:is_shelf', [':id' => $org_id, ':status' => UyeOrg::STATUS_OK, ':is_shelf' => UyeOrg::IS_SHELF_ON])
            ->asArray()
            ->one();
        return $this->render('view', $orgInfo);

    }
}