<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/12
 * Time: 下午7:41
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeConfig;
use common\models\ar\UyeUserQuestion;
use components\Output;
use components\RedisUtil;
use components\UException;
use frontend\models\DataBus;

class QuestionController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function actions()
    {
        return [
            'submit' => [
                'class' => 'app\modules\app\actions\QuestionAction'
            ],
        ];
    }

    public function actionConfig()
    {
        try {
            $org_id = $this->getParams('org_id');
            if (empty($org_id)) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT, ERROR_SYS_PARAMS);
            }
            //根据机构id和用户uid检查是否填写过
            $userQuestion = UyeUserQuestion::getByUidAndOrgID($this->uid, $org_id);
            if (empty($userQuestion)) {
                $config = UyeConfig::getConfig('question');
                $data = json_decode($config['value']);
                $needQuestion = true;
            } else {
                $needQuestion = false;
                $data = [];
            }
            $templateData = [
                'need_question' => $needQuestion,
                'questions' => $data,
            ];
            Output::info(SUCCESS, SUCCESS_CONTENT, $templateData);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}