<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/11/16
 * Time: 上午11:20
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use app\modules\app\models\WorkModel;
use common\models\ar\UyeInsuredOrder;
use common\models\ar\UyeInsuredWork;
use components\Output;
use components\UException;

class WorkController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    public function actions()
    {
        return [
            'submit' => [
                'class' => "app\modules\app\actions\WorkAction",
            ],
        ];
    }

    public function actionConfig()
    {
        try {
            $config = [
                'monthly_income' => ['2000以下', '2000~5000', '5000~8000', '8000~20000', '20000以上'],
            ];
            Output::info(SUCCESS, SUCCESS_CONTENT, $config);
        } catch (UException $exception) {
            Output::err($exception->getMessage(), $exception->getCode());
        }
    }

    public function actionList()
    {
        try {
            $insured_id = $this->getParams('insured_id');
            $page = $this->getParams('page', 1);
            if (empty($insured_id) || !is_numeric($insured_id) || !is_numeric($page)) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT, ERROR_SYS_PARAMS);
            }
            $insured = UyeInsuredOrder::getOrderByID($insured_id);
            if (empty($insured) || $insured['uid'] != $this->uid) {
                throw new UException(ERROR_INSURED_NOT_EXISTS_CONTENT, ERROR_INSURED_NOT_EXISTS);
            }

            $data = WorkModel::getList($insured_id, $page);

            Output::info(SUCCESS, SUCCESS_CONTENT, $data);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}