<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/11/16
 * Time: 上午11:20
 */

namespace app\modules\app\controllers;


use app\modules\app\components\AppController;
use common\models\ar\UyeInsuredOrder;
use common\models\ar\UyeInsuredWork;
use components\Output;
use components\UException;

class WorkController extends AppController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        $this->checkLogin();
    }

    public function actions()
    {
        return [
            'submit' => [
                'class' => "app\modules\app\actions\WorkAction",
            ],
        ];
    }

    public function actionConfig()
    {
        try {
            $config = [
                'monthly_income' => ['2000以下', '2000~5000', '5000~8000', '8000~20000', '20000以上'],
            ];
            Output::info(SUCCESS, SUCCESS_CONTENT, $config);
        } catch (UException $exception) {
            Output::err($exception->getMessage(), $exception->getCode());
        }
    }

    public function actionList()
    {
        try {
            $insured_id = $this->getParams('insured_id');
            if (empty($insured_id) || !is_numeric($insured_id)) {
                throw new UException(ERROR_SYS_PARAMS_CONTENT, ERROR_SYS_PARAMS);
            }
            $insured = UyeInsuredOrder::getOrderByID($insured_id);
            if (empty($insured) || $insured['uid'] != $this->uid) {
                throw new UException(ERROR_INSURED_NOT_EXISTS_CONTENT, ERROR_INSURED_NOT_EXISTS);
            }

            $lists = UyeInsuredWork::getListByInsuredID($insured_id);
            $works = [];
            foreach ($lists as $list) {
                $tmp = [
                    'date' => $list['date'], 'desp' => '', 'pic' => []
                ];

                if (is_array(json_decode($list['pic_json'], true))) {
                    $tmp['pic'] = json_decode($list['pic_json'], true);
                }

                switch ($list['is_hiring']) {
                    case UyeInsuredWork::IS_HIRING_SUCCESS:
                        $desp = "恭喜您成功就业到" . $list['work_name'] . '!';
                        break;
                    case UyeInsuredWork::IS_HIRING_WAIT:
                        if ($list['add_type'] == 1) {
                            $desp = "您尝试就业到" . $list['work_name'];
                        } else {
                            $desp = "机构为您推荐就业到" . $list['work_name'];
                        }
                        break;
                }
                $tmp['desp'] = $desp;
                $works[] = $tmp;
            }
            Output::info(SUCCESS, SUCCESS_CONTENT, $works);
        } catch (UException $exception) {
            Output::err($exception->getCode(), $exception->getMessage());
        }
    }
}