<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/17
 * Time: 上午11:23
 */

define('INSURED_STATUS_CREATE', 100);
define('INSURED_STATUS_CREATE_CONTENT', "审核中");

define('INSURED_STATUS_VERIFY_PASS', 150);
define('INSURED_STATUS_VERIFY_PASS_CONTENT', "投保中");

define('INSURED_STATUS_VERIFY_REFUSE', 151);
define('INSURED_STATUS_VERIFY_REFUSE_CONTENT', "审核拒绝");

define('INSURED_STATUS_PAYMENT', 200);
define('INSURED_STATUS_PAYMENT_CONTENT', "培训中");

define('INSURED_STATUS_STUDYING', 300);
define('INSURED_STATUS_STUDYING_CONTENT', "择业中");
