<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/15
 * Time: 下午3:46
 */

namespace app\modules\e\components;


use app\modules\e\models\EDataBus;
use yii\web\Controller;

class EController extends Controller
{
    protected $user;
    protected $uid;
    private $org_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = "main";
        $this->checkLogin();
        $this->user = EDataBus::get('user');
        $this->uid = EDataBus::get('uid');
        $this->org_id = $this->user['org_id'];

        return $this->render("default/error",['']);
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * 查询当前登录态
     * @return array|mixed
     */
    protected function isLogin()
    {
        return EDataBus::get('isLogin');
    }

    /**
     * 检查是否登录,未登录直接条状登录
     * @return array|mixed
     */
    protected function checkLogin()
    {
        if (!$this->isLogin()) {
            $this->redirect('/e/login/login');
        } else {
            return $this->isLogin();
        }
    }
}