<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/12/12
 * Time: 下午2:06
 */

namespace e\controllers;


use common\models\ar\UyeInsuredOrder;
use common\models\service\SimgService;
use components\PicUtil;
use components\UException;
use e\components\EController;
use e\components\EOutput;

class CommonController extends EController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }

    /**
     * 上传
     */
    public function actionUpload()
    {

        try {
            $id = $this->getParams('id');
            $insuredInfo = UyeInsuredOrder::getOrderByID($id);
            if (empty($insuredInfo)) {
                throw new UException(ERROR_INSURED_NOT_EXISTS_CONTENT, ERROR_INSURED_NOT_EXISTS);
            }

            if ($this->org_id != $insuredInfo['org_id']) {
                throw new UException();
            }

            $fileInfo = [];
            $ret = PicUtil::uploadPic(PicUtil::SECRET_ADMIN, [], $fileInfo, [], $insuredInfo['uid']);
            $ret = PicUtil::getUrls($ret, PicUtil::SECRET_ADMIN);
            SimgService::addSimgInfo($ret, $insuredInfo['uid']);
            EOutput::info(SUCCESS, SUCCESS_CONTENT, $ret);
        } catch (UException $exception) {
            EOutput::err($exception->getCode(), $exception->getMessage());
        }
    }
}