<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/20
 * Time: 下午12:00
 */

namespace e\controllers;

use common\models\ar\UyeInsuredOrder;
use e\models\service\InsuredModel;
use Yii;
use common\models\search\UyeInsuredOrderSearch;
use e\components\EController;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class InsuredController extends EController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {

    }

    public function actionList()
    {
        $searchModel = new UyeInsuredOrderSearch();
        $queryParams = Yii::$app->request->queryParams;

        $queryParams['UyeInsuredOrderSearch']['org_id'] = Yii::$app->user->identity->org_id;
        $dataProvider = $searchModel->search($queryParams);
        $dataProvider->pagination->defaultPageSize = 10;
        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $templateData = InsuredModel::getInsuredInfo($id, Yii::$app->user->identity->org_id);
        return $this->render('view', $templateData);
    }

    protected function findModel($id)
    {
        if (($model = UyeInsuredOrder::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}