<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/20
 * Time: 下午12:00
 */

namespace e\controllers;

use Yii;
use common\models\search\UyeInsuredOrderSearch;
use e\components\EController;
use yii\filters\VerbFilter;

class InsuredController extends EController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {

    }

    public function actionList()
    {
        $searchModel = new UyeInsuredOrderSearch();
        $queryParams = Yii::$app->request->queryParams;
        $queryParams['org_id'] = Yii::$app->user->identity->org_id;
        $dataProvider = $searchModel->search($queryParams);
        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}