<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/20
 * Time: 上午10:48
 */

namespace e\controllers;


use e\components\EController;

class LoginController extends EController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}