<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/12/1
 * Time: 下午3:43
 */

namespace e\controllers;


use common\models\ar\UyeInsuredOrder;
use components\CsvUtil;
use components\UException;
use e\components\EController;

use e\components\EOutput;
use e\models\service\InsuredModel;
use e\models\service\StudyModel;
use Yii;

class StudyController extends EController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }

    /**
     * 学习中的保单列表
     * @return string
     */
    public function actionIndex()
    {
        $excel = Yii::$app->request->get('excel');
        $params = Yii::$app->request->queryParams;
        $params['insured_status'] = INSURED_STATUS_STUDYING;
        $data = InsuredModel::getInsuredOrders($params, $this->org_id);
        if (!$excel) {
            return $this->render('index', $data);
        } else {
            $headerData = ['单号', '状态', '姓名', '身份证号', '手机号', '分校', '课程', '顾问', '申请时间', '支付时间', '学费', '服务费'];
            $list = [];
            foreach ($data as $item) {
                $tmp = [
                    $item['insured_order'],
                    UyeInsuredOrder::getInsuredStatusDesp($item['insured_status']),
                    $item['full_name'],
                    $item['id_card'],
                    $item['auth_mobile'],
                    $item['org_name'],
                    $item['c_name'],
                    $item['course_consultant'],
                    date('Y-m-d H:i:s', $item['created_time']),
                    date('Y-m-d H:i:s', $item['created_time']),
                    "￥" . number_format(($item['tuition'] / 100), 2),
                    "￥" . number_format(($item['premium_amount'] / 100), 2)
                ];
                $list[] = $tmp;
            }

            CsvUtil::exportCsv($list, $headerData, "Uye_" . date('YmdHis') . ".csv");
        }
    }

    /**
     * 已毕业操作
     */
    public function actionGraduation()
    {
        try {
            $insured_id = $this->getParams('id');
            StudyModel::graduation($insured_id, $this->user['uid'], $this->org_id);
            EOutput::info(SUCCESS, SUCCESS_CONTENT);
        } catch (UException $exception) {
            EOutput::err($exception->getCode(), $exception->getMessage());
        }
    }

    /**
     * 新增学习经历
     */
    public function actionAdd()
    {
        $id = $this->getParams('id');
        $type = $this->getParams('type');
        if ($type == '_add') {
            $params = $_POST;
            try {
                StudyModel::addStudyList($params, $this->user['uid'], $this->org_id);
                EOutput::info(SUCCESS, SUCCESS_CONTENT);
            } catch (UException $exception) {
                EOutput::err($exception->getCode(), $exception->getMessage());
            }
        } else {
            $insured = UyeInsuredOrder::getOrderByID($id);
            return $this->render('add', ['insured' => $insured]);
        }
    }
}