<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/22
 * Time: 下午3:54
 */

namespace e\components;

use common\models\ar\UyeELog;
use common\models\ar\UyeOrg;
use components\UException;
use Yii;
use yii\base\NotSupportedException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class EController extends Controller
{
    public $org_id;
    public $org;
    public $user;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (Yii::$app->user->isGuest) {
            $this->addLog(true);
            header('Location:/login/login');
        }

        $this->checkRight();
        $this->org_id = Yii::$app->user->identity->org_id;
        $this->org = $this->getOrgInfo();
        $this->addLog();

    }

    public function checkRight()
    {
        $user = RbacUtil::checkUserRight(Yii::$app->user->identity->id);
        if (empty($user)) {
            $this->addLog(true);
            throw new NotSupportedException("权限不足");
        } else {
            Yii::$app->params['userInfo'] = $user;
            $this->user = $user;
        }
    }

    /**
     * @param string $key
     * @return array|mixed
     */
    public function getParams($key = '')
    {
        $request = Yii::$app->request;

        $method = strtolower($request->method);
        switch ($method) {
            case 'get':
                return $request->get($key);
                break;
            case 'post':
                return $request->post($key);
                break;
            default:
                return '';
                break;
        }
    }

    public function getOrgInfo()
    {
        $orgInfo = UyeOrg::getOrgById($this->org_id, null, null, true);
        if (empty($orgInfo)) {
            throw new NotFoundHttpException(ERROR_ORG_NOT_EXISTS_CONTENT, ERROR_ORG_NOT_EXISTS);
        }
        return $orgInfo;
    }

    private function addLog($isGust = false)
    {
        $info = [];
        foreach ($_SERVER as $key => $item) {
            $info[strtolower($key)] = $item;
        }

        if ($isGust) {
            $info['uid'] = 0;
            $info['org_id'] = 0;
            $info['role_name'] = '访客';
        } else {
            $info['uid'] = $this->user['id'];
            $info['org_id'] = $this->user['org_id'];
            $info['role_name'] = $this->user['role_name'];
        }

        if ($info['request_method'] != 'GET') {
            $info['query_string'] = $info['query_string'] . '|' . http_build_query($_POST);
        }

        try {
            UyeELog::_add($info);
        } catch (UException $exception) {
            Yii::error($exception->getMessage());
        }
    }

}