<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/15
 * Time: 下午3:45
 */

namespace app\modules\app\components;


use frontend\components\UController;

class AppController extends UController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}