<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/15
 * Time: 下午3:45
 */

namespace app\modules\app\components;

use Yii;
use frontend\components\UController;

class AppController extends UController
{
    public $version = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->version = $this->getParams('version');
    }

    /**
     * @param string $key
     * @return array|mixed
     */
    public function getParams($key = '')
    {
        $request = Yii::$app->request;

        $method = strtolower($request->method);
        switch ($method) {
            case 'get':
                return $request->get($key);
                break;
            case 'post':
                return $request->post($key);
                break;
            default:
                return '';
                break;
        }
    }
}