<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/15
 * Time: 下午3:50
 */

namespace common\models\ar;


use yii\db\ActiveRecord;

class UActiveRecord extends ActiveRecord
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}