<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/21
 * Time: 下午5:45
 */

namespace common\models\ar;


class UyeAdminMenu extends UActiveRecord
{
    const TABLE_NAME = 'uye_admin_menu';


    public static function tableName()
    {
        return self::TABLE_NAME; // TODO: Change the autogenerated stub
    }

    public static function getMenus()
    {
        return self::find()->select('*')->where('status=:status', [':status' => 1])->asArray()->all();
    }

    public static function getMenuByRoute($route)
    {
        return self::find()->select('*')->where('route=:route', [':route' => $route])->asArray()->one();
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '菜单id',
            'name' => '菜单名称',
            'parent' => '父级菜单',
            'route' => '路由',
            'order' => '排序'
        ];
    }
}