<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/21
 * Time: 下午5:45
 */

namespace common\models\ar;


class UyeAdminMenu extends UActiveRecord
{
    const TABLE_NAME = 'uye_admin_menu';


    public static function tableName()
    {
        return self::TABLE_NAME; // TODO: Change the autogenerated stub
    }

    public static function getMenus()
    {
        return self::find()->select('*')->where('status=:status', [':status' => 1])->asArray()->all();
    }

    public static function getMenuByRoute($route)
    {
        return self::find()->select('*')->where('route=:route', [':route' => $route])->asArray()->one();
    }
}