<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/21
 * Time: 下午5:45
 */

namespace common\models\ar;


class UyeAdminMenu extends UActiveRecord
{
    const TABLE_NAME = 'uye_admin_menu';


    public static function tableName()
    {
        return self::TABLE_NAME; // TODO: Change the autogenerated stub
    }

    public static function getMenus()
    {
        return self::find()->select('*')->where('status=:status', [':status' => 1])->asArray()->all();
    }

    public static function createMenus()
    {
        $menus = self::getMenus();

        $menuItems = [];

        foreach ($menus as $key => $menu) {
            if ($menu['parent'] == 0) {
                $menuItems[$menu['id']] = array(
                    'icon' => $menu['icon'],
                    'label' => $menu['name'],
                    'url' => $menu['route'],
                    'options' => [],
                    'item' => []
                );
                unset($menus[$key]);
            }
        }

        foreach ($menus as $key => $menu) {
            if (array_key_exists($menu['parent'], $menuItems)) {
                $menuItems[$menu['parent']]['item'][$menu['id']] = array(
                    'icon' => $menu['icon'],
                    'label' => $menu['name'],
                    'url' => $menu['route'],
                    'options' => [],
                    'item' => []
                );
            }
        }
        return $menuItems;
    }
}