<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/10
 * Time: 下午7:20
 */

namespace common\models\ar;


class UyeOrgCourse extends UActiveRecord
{
    const TABLE_NAME = 'uye_org_course';

    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public static function getCoursesListByOrgID($org_id)
    {
        if (!is_numeric($org_id) || is_null($org_id)) {
            return [];
        }

        $courses = self::find()
            ->select('*')
            ->from(self::TABLE_NAME)
            ->where('org_id=:org_id', [':org_id' => $org_id])
            ->asArray()
            ->all();

        if (empty($courses)) {
            return [];
        } else {
            return $courses;
        }
    }
}