<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/10
 * Time: 下午7:20
 */

namespace common\models\ar;


use components\ArrayUtil;
use components\UException;

class UyeOrgCourse extends UActiveRecord
{
    const TABLE_NAME = 'uye_org_course';

    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public static function getCoursesListByOrgID($org_id)
    {
        if (!is_numeric($org_id) || is_null($org_id)) {
            return [];
        }

        $courses = self::find()
            ->select('*')
            ->from(self::TABLE_NAME)
            ->where('org_id=:org_id', [':org_id' => $org_id])
            ->asArray()
            ->all();

        if (empty($courses)) {
            return [];
        } else {
            return $courses;
        }
    }

    public static function _add($info)
    {
        if (empty($info)) {
            return false;
        }

        $info = ArrayUtil::trimArray($info);

        $ar = new UyeOrgCourse();
        $ar->setIsNewRecord(true);
        foreach ($ar->getAttributes() as $key => $attribute) {
            if (array_key_exists($key, $info)) {
                $ar->$key = $info[$key];
            }
        }

        $ar->created_time = time();
        $ar->updated_time = time();

        if (!$ar->save()) {
            UException::dealAR($ar);
        }
        return $ar->getAttributes();
    }

    public static function getAvgUnitByOrgID($org_id)
    {
        if (!is_numeric($org_id)) {
            return 0;
        }

        $result = UyeOrgCourse::find()
            ->select('AVG(unit_price) AS avg_unit_price')
            ->from(self::TABLE_NAME)
            ->where('org_id=:org_id', [':org_id' => $org_id])
            ->asArray()
            ->one();
        return $result['avg_unit_price'];
    }
}