<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/10/10
 * Time: 下午7:20
 */

namespace common\models\ar;


class UyeOrgCourse extends UActiveRecord
{
    const TABLE_NAME = 'uye_org_course';

    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
}