<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/18
 * Time: 下午3:38
 */

namespace common\models\ar;


use components\ArrayUtil;

class UyeSmsRecore extends UActiveRecord
{
    const TABLE_NAME = 'uye_sms_record';

    const TYPE_SMS_VERIFY_CODE = 1;


    public static function tableName()
    {
        return self::TABLE_NAME; // TODO: Change the autogenerated stub
    }


    public static function _addInfo($info = array())
    {
        if (empty($info)) {
            return false;
        }

        $ar = new UyeSmsRecore();
        $ar->setIsNewRecord(true);
        $attributes = $ar->getAttributes();
        $info = ArrayUtil::trimArray($info);

        foreach ($attributes as $key => $attribute) {
            if (!empty($info[$key])) {
                $ar->$key = $info[$key];
            }
        }

        if (!$ar->save()) {
            return false;
        }

        return $ar->getAttributes();
    }
}