<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/22
 * Time: 下午3:54
 */

namespace backend\components;

use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

class UAdminController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return true;
        }
    }


}