<?php
/**
 * Created by PhpStorm.
 * User: wangyi
 * Date: 2017/9/22
 * Time: 下午3:54
 */

namespace backend\components;

use common\models\ar\UyeAdminLog;
use components\UException;
use Yii;
use yii\web\Controller;

class UAdminController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function beforeAction($action)
    {
        $this->addLog();
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        } else {
            return true;
        }
    }

    public function getParams($key = '')
    {
        $request = Yii::$app->request;

        $method = strtolower($request->method);
        switch ($method) {
            case 'get':
                return $request->get($key);
                break;
            case 'post':
                return $request->post($key);
                break;
            default:
                return '';
                break;
        }
    }

    private function addLog()
    {
        $info = [];
        foreach ($_SERVER as $key => $item) {
            $info[strtolower($key)] = $item;
        }

        if (Yii::$app->user->isGuest) {
            $info['uid'] = 0;
        } else {
            $info['uid'] = Yii::$app->user->id;
        }

        if ($info['request_method'] != 'GET') {
            $info['query_string'] = $info['query_string'] . '|' . http_build_query($_POST);
        }
        try {
            UyeAdminLog::_add($info);
        } catch (UException $exception) {
            Yii::error($exception->getMessage());
        }
    }
}